# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('optional_tag_under_name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bio', models.TextField()),
            ],
        ),
    ]
