# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('optional_tag_under_name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('company', models.URLField(blank=True)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='company',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
