# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20161206_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisors',
            old_name='company',
            new_name='company_url',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='company',
            new_name='company_url',
        ),
        migrations.AddField(
            model_name='advisors',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='advisors',
            name='img',
            field=models.ImageField(upload_to=pages.models.img_upload_handler),
        ),
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(upload_to=pages.models.img_upload_handler),
        ),
    ]
